import type { BotRules } from "@/lib/types";

export const defaultRules: BotRules = {
  enabled: true,
  botName: "Tarik",
  defaultReply: "Hello! Ji, aapka message mila. Thoda detail mein batayenge to behtar samajh paunga.",
  greetingReply: "Hello! Ji farmayiye, sab theek thaak? Boliye, main kaise help kar sakta hoon?",
  includeName: false,
  useLocalLlm: true,
  preferredModel: "",
  language: "english",
  tone: "warm",
  emoji: false,
  signature: "",
  customFacts: "",
  replyMode: "all",
  replyToMedia: true,
  replyToGroups: false,
  showTyping: true,
  businessHoursEnabled: false,
  timezone: "Asia/Kolkata",
  openHour: 9,
  closeHour: 21,
  afterHoursReply: "I am currently offline outside business hours. I will review your message and reply as soon as possible.",
  keywordRules: [
    {
      id: "salam",
      keyword: "salam",
      reply: "Walaikum Assalam! Khairiyat? Boliye, main kis tarah madad kar sakta hoon?",
      enabled: true,
    },
    {
      id: "namaste",
      keyword: "namaste",
      reply: "Namaste! Boliye, sab theek thaak? Kis cheez mein madad chahiye?",
      enabled: true,
    },
    {
      id: "hello",
      keyword: "hello",
      reply: "Hello! Ji boliye, sab theek thaak? Kis cheez mein madad chahiye?",
      enabled: true,
    },
    {
      id: "hi",
      keyword: "hi",
      reply: "Hello! Ji farmayiye, sab theek thaak? Boliye, main kaise help kar sakta hoon?",
      enabled: true,
    },
    {
      id: "hours",
      keyword: "hours",
      reply: "Operating in IST (UTC+05:30). Typical response time is under 24 hours.",
      enabled: true,
    },
    {
      id: "price",
      keyword: "price",
      reply: "Pricing depends on project scope and technical requirements. Please share your project details.",
      enabled: true,
    },
  ],
};
