import type { BotRules } from "@/lib/types";

export const defaultRules: BotRules = {
  enabled: true,
  botName: "Tarik",
  defaultReply: "Received your message. How can I help you?",
  greetingReply: "Hello! How can I help you today?",
  includeName: false,
  useLocalLlm: true,
  preferredModel: "",
  language: "english",
  tone: "warm",
  emoji: false,
  signature: "",
  customFacts: "",
  replyMode: "all",
  replyToMedia: true,
  replyToGroups: false,
  showTyping: true,
  businessHoursEnabled: false,
  timezone: "Asia/Kolkata",
  openHour: 9,
  closeHour: 21,
  afterHoursReply: "I am currently offline outside business hours. I will review your message and reply as soon as possible.",
  keywordRules: [
    {
      id: "hello",
      keyword: "hello",
      reply: "Hello! How can I help you today?",
      enabled: true,
    },
    {
      id: "hi",
      keyword: "hi",
      reply: "Hi there! How can I assist you?",
      enabled: true,
    },
    {
      id: "hours",
      keyword: "hours",
      reply: "Operating in IST (UTC+05:30). Typical response time is under 24 hours.",
      enabled: true,
    },
    {
      id: "price",
      keyword: "price",
      reply: "Pricing depends on project scope and technical requirements. Please share your project details.",
      enabled: true,
    },
  ],
};
